name: yss_app
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.5 <4.0.0'

dependencies: 
  get: 4.6.6
  material_design_icons_flutter: ^7.0.7296
  intl: ^0.19.0
  image_picker: ^1.0.7
  get_storage: ^2.1.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/icons/

